# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d9ad046cf8fb905cbd3e5cdd1f5b5a65f3461ee230c8348c70d0d746eacd65d34244916fc99eee3ee6876678a8780afe1fae004794b78ae40d6a31730627840

test:
  secret_key_base: 32dceb57612e4b426a69e2b0e40c12ab17e87ddbf1a393c051af0da68b6e216d274a5a0465c676cdedaf1e751cd7677d5dc272b7f30603e6f16a43f225516de0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
